server:
    port: 8081
spring:
    freemarker:
        suffix: .ftl
    datasource:
        username: "root"
        url: jdbc:mariadb://localhost:3306/prodDB
        driver-class-name: org.mariadb.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
            maximum-pool-size: 20
    flyway:
        baseline-on-migrate: false
        locations: "classpath:db/migration"
