server:
    port: 8081
spring:
    freemarker:
        suffix: .ftl
    datasource:
        username: "root"
        url: jdbc:mariadb://localhost:3306/users
        driver-class-name: org.mariadb.jdbc.Driver
    flyway:
        baseline-on-migrate: false
        locations: "classpath:db/migration"
